# Generated by Django 6.0.1 on 2026-01-17 16:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('ordre', models.IntegerField(default=1)),
                ('video', models.FileField(upload_to='tutoriels/videos/')),
                ('texte_explicatif', models.TextField()),
                ('duree', models.IntegerField(help_text='Durée en secondes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('niveau', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé')], default='DEBUTANT', max_length=20)),
                ('ordre', models.IntegerField(default=1, help_text="Ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True)),
                ('difficulte', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='tutoriels/couvertures/')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pass_mark', models.IntegerField(default=70, help_text='Score minimum pour réussir (%)')),
                ('difficulte', models.IntegerField(choices=[(1, 'Facile'), (2, 'Moyen'), (3, 'Difficile')], default=1)),
                ('temps_limite', models.IntegerField(default=300, help_text='Temps limite en secondes (0 = pas de limite)')),
                ('lecon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='tutoriel.lecon')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('type_question', models.CharField(choices=[('CHOIX_MULTIPLE', 'Choix multiple'), ('VRAI_FAUX', 'Vrai ou Faux')], default='CHOIX_MULTIPLE', max_length=20)),
                ('ordre', models.IntegerField(default=1)),
                ('points', models.IntegerField(default=1, help_text='Points pour cette question')),
                ('explication', models.TextField(blank=True, help_text='Explication après réponse')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tutoriel.quiz')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_text', models.CharField(max_length=500)),
                ('est_correcte', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='tutoriel.question')),
            ],
        ),
        migrations.AddField(
            model_name='lecon',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='tutoriel.tutorial'),
        ),
        migrations.CreateModel(
            name='ProgressionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_completee', models.BooleanField(default=False)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('score_quiz', models.IntegerField(blank=True, help_text='Score du quiz associé (%)', null=True)),
                ('temps_passe', models.IntegerField(default=0, help_text='Temps passé en secondes')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoriel.lecon')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression', to=settings.AUTH_USER_MODEL)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoriel.tutorial')),
            ],
            options={
                'verbose_name_plural': 'Progressions Utilisateurs',
                'unique_together': {('utilisateur', 'lecon')},
            },
        ),
    ]
