# Generated by Django 6.0.1 on 2026-01-15 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraductionAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_original', models.TextField(help_text='Texte en français à convertir en signes', verbose_name='Texte à traduire')),
                ('langue_parlee', models.CharField(choices=[('de', 'Allemand'), ('fr', 'Français'), ('it', 'Italien')], default='fr', max_length=10, verbose_name='Langue parlée')),
                ('langue_signee', models.CharField(choices=[('sgg', 'Langue des signes suisse-allemande'), ('ssr', 'Langue des signes française de Suisse'), ('slf', 'Langue des signes italienne de Suisse')], default='ssr', max_length=10, verbose_name='Langue signée')),
                ('fichier_pose', models.FileField(blank=True, null=True, upload_to='avatars/poses/%Y/%m/%d/', verbose_name='Fichier pose généré')),
                ('video_generee', models.FileField(blank=True, null=True, upload_to='avatars/videos/%Y/%m/%d/', verbose_name='Vidéo générée')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_traitement', 'En traitement'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_attente', max_length=20)),
                ('message_erreur', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('temps_traitement', models.FloatField(blank=True, null=True, verbose_name='Temps de traitement (secondes)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traductions_avatar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traduction Avatar',
                'verbose_name_plural': 'Traductions Avatar',
                'ordering': ['-date_creation'],
            },
        ),
    ]
