# Generated by Django 6.0.1 on 2026-01-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar_signeur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traductionavatar',
            name='langue_signee',
            field=models.CharField(choices=[('sgg', 'Langue des signes suisse-allemande'), ('ssr', 'Langue des signes française de Suisse'), ('slf', 'Langue des signes italienne de Suisse'), ('mar', 'Langue des signes marocaine')], default='mar', max_length=10, verbose_name='Langue signée'),
        ),
    ]
